// Auth
export const LOGIN_USER_REQUEST = 'auth/LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'auth/LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'auth/LOGIN_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'auth/REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'auth/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'auth/REGISTER_USER_FAILURE';
export const CLEAR_AUTH_TOKEN_REQUEST = 'auth/CLEAR_AUTH_TOKEN_REQUEST';
export const CLEAR_AUTH_TOKEN_SUCCESS = 'auth/CLEAR_AUTH_TOKEN_SUCCESS';
export const CLEAR_AUTH_TOKEN_FAILURE = 'auth/CLEAR_AUTH_TOKEN_FAILURE';


// UI
export const SET_SIDEBAR_ITEM_REQUEST = 'ui/SET_SIDEBAR_ITEM_REQUEST';
export const SET_SIDEBAR_ITEM_SUCCESS = 'ui/SET_SIDEBAR_ITEM_SUCCESS';
export const SET_SIDEBAR_ITEM_FAILURE = 'ui/SET_SIDEBAR_ITEM_FAILURE';

// Students
export const LIST_STUDENTS_REQUEST = 'students/LIST_STUDENTS_REQUEST';
export const LIST_STUDENTS_SUCCESS = 'students/LIST_STUDENTS_SUCCESS';
export const LIST_STUDENTS_FAILURE = 'students/LIST_STUDENTS_FAILURE';
export const REMOVE_STUDENTS_REQUEST = 'admin/REMOVE_STUDENTS_REQUEST';
export const REMOVE_STUDENTS_SUCCESS = 'admin/REMOVE_STUDENTS_SUCCESS';
export const REMOVE_STUDENTS_FAILURE = 'admin/REMOVE_STUDENTS_FAILURE';
export const CREATE_STUDENTS_REQUEST = 'admin/CREATE_STUDENTS_REQUEST';
export const CREATE_STUDENTS_SUCCESS = 'admin/CREATE_STUDENTS_SUCCESS';
export const CREATE_STUDENTS_FAILURE = 'admin/CREATE_STUDENTS_FAILURE';

// Admin
export const LIST_ADMIN_REQUEST = 'admin/LIST_ADMIN_REQUEST';
export const LIST_ADMIN_SUCCESS = 'admin/LIST_ADMIN_SUCCESS';
export const LIST_ADMIN_FAILURE = 'admin/LIST_ADMIN_FAILURE';
export const REMOVE_ADMIN_REQUEST = 'admin/REMOVE_ADMIN_REQUEST';
export const REMOVE_ADMIN_SUCCESS = 'admin/REMOVE_ADMIN_SUCCESS';
export const REMOVE_ADMIN_FAILURE = 'admin/REMOVE_ADMIN_FAILURE';
export const CREATE_ADMIN_REQUEST = 'admin/CREATE_ADMIN_REQUEST';
export const CREATE_ADMIN_SUCCESS = 'admin/CREATE_ADMIN_SUCCESS';
export const CREATE_ADMIN_FAILURE = 'admin/CREATE_ADMIN_FAILURE';

// Staff
export const LIST_STAFF_REQUEST = 'staff/LIST_STAFF_REQUEST';
export const LIST_STAFF_SUCCESS = 'staff/LIST_STAFF_SUCCESS';
export const LIST_STAFF_FAILURE = 'staff/LIST_STAFF_FAILURE';
export const REMOVE_STAFF_REQUEST = 'admin/REMOVE_STAFF_REQUEST';
export const REMOVE_STAFF_SUCCESS = 'admin/REMOVE_STAFF_SUCCESS';
export const REMOVE_STAFF_FAILURE = 'admin/REMOVE_STAFF_FAILURE';
export const CREATE_STAFF_REQUEST = 'admin/CREATE_STAFF_REQUEST';
export const CREATE_STAFF_SUCCESS = 'admin/CREATE_STAFF_SUCCESS';
export const CREATE_STAFF_FAILURE = 'admin/CREATE_STAFF_FAILURE';
